# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HostBarTracker-CashCalculator' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HostBarTracker-CashCalculator

  pod 'Firebase'

  target 'HostBarTracker-CashCalculatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HostBarTracker-CashCalculatorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
